:development: &default_config
  :storage:
    :redis:
      :host: 'localhost'
      :port: 6379
    :namespace: 'kata'

:test:
  <<: *default_config

:stage:
  <<: *default_config

:production:
  <<: *default_config
  :storage:
    :redis:
      :password: 'wKdNOMiu8UY6xMly'
      :host: 'pub-redis-18975.eu-west-1-1.2.ec2.garantiadata.com'
      :port: 18975
    :namespace: 'kata'
